export const actions = {
    CLICK_NUMBER: 'CLICK_NUMBER',
    CLICK_C: 'CLICK_C',
    CLICK_PERCENT: 'CLICK_PERCENT',
    CLICK_MINMAX: 'CLICK_MINMAX',
    CLICK_OPERATOR: 'CLICK_OPERATOR',
    CLICK_EQUAL: 'CLICK_EQUAL',
};